#!/bin/sh

CALC_DIR=/home/daq
NSDAQ_DIR=/home/daq/NSdaq

libreoffice --headless --convert-to csv --outdir $CALC_DIR ${CALC_DIR}/ns-registers.ods
${NSDAQ_DIR}/control/set-registers ${CALC_DIR}/ns-registers.csv
